schema_version: 20180708
name: fibonacci-function
version: 0.0.1
runtime: java8
build_image: fnproject/fn-java-fdk-build:1.0.100
run_image: fnproject/fn-java-fdk:1.0.100
cmd: com.simcode.fnproject.calculatorapp.fibonacci.FibonacciFunction::handleRequest
timeout: 180
triggers:
  - name: fibonacci-function-trigger
    type: http
    source: /fibonacci
