schema_version: 20180708
name: subtract-function
version: 0.0.1
runtime: java8
build_image: fnproject/fn-java-fdk-build:1.0.85
run_image: fnproject/fn-java-fdk:1.0.85
cmd: com.simcode.fnproject.calculatorapp.subtract.SubtractFunction::handleRequest
format: http
triggers:
  - name: subtract-function-trigger
    type: http
    source: /subtract
