schema_version: 20180708
name: simple-function
version: 0.0.3
runtime: java8
build_image: fnproject/fn-java-fdk-build:1.0.100
run_image: fnproject/fn-java-fdk:1.0.100
cmd: com.example.fn.HelloFunction::handleRequest
triggers:
- name: simple-function
  type: http
  source: /simple-function
