schema_version: 20180708
name: simple-function
version: 0.0.3
runtime: java8
build_image: fnproject/fn-java-fdk-build:1.0.85
run_image: fnproject/fn-java-fdk:1.0.85
cmd: com.example.fn.HelloFunction::handleRequest
format: http-stream
triggers:
- name: simple-function-trigger
  type: http
  source: /simple-function-trigger
